name: Pull Request Check

on: pull_request

jobs:
  smoketest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Since it's hard to test these scripts without an actual board, we only do a minimal sanity check by building the
      # example.
      - name: test
        run: |
          docker run \
            --rm \
            --privileged \
            --entrypoint /bin/bash \
            -v /dev:/dev \
            -v ${PWD}/examples/raspberry-pi-3:/build \
            mkaczanowski/packer-builder-arm:1.0.3 \
            -c "/entrypoint.sh init raspios-lite-arm64.pkr.hcl && /entrypoint.sh build -var arm_packer_common_version=${{ github.sha }} raspios-lite-arm64.pkr.hcl"
